### ISSUE TITLE
Add support for Single Directory Components (SDC)

### ISSUE THREAD

**Issue by estebanpcastro** [larowlan/vite-plugin-twig-drupal#17]
When I use this kind of sintaxis to embed other twig file with SDC, I got an error 

"Pre-transform error: Failed to resolve import"
"Does the file exist?  Plugin: vite:import-analysis"

Do you know if I need to add extra config, thanks in advance

**Comment by larowlan** [comment]
Can you share your twig file?

**Comment by estebanpcastro** [comment]
Sure here is 

<div{{ attributes.addClass(classes) }}>
    {% block content %}
      {% embed 'web_foundation:button' with {
        button_html_tag: 'a',
        url: url,
        color: button_style,
        disabled: button_disabled,
        button_attributes: button_attributes,
        content: content,
      } %}
         <span> {{ link }} </span>{{ icon_link|raw }}
      {% endembed %}
    {% endblock %}
  </div>

As you can see, I'm trying to embed another component Button that already works

**Comment by larowlan** [comment]
What have you configured for namespaces in the twig options for your vite.config.js
I've not seen that syntax before, I would have expect it would need `@web_foundation/button/button.twig` if you have mapped @web_foundation somewhere.

Are you using something custom in Drupal to support `web_foundation:button`?

**Comment by estebanpcastro** [comment]
I'm using [SDC](https://www.drupal.org/project/sdc) in Drupal is not custom implementation.

How I can map @web_foundation as the folder path to the custom theme?

**Comment by larowlan** [comment]
There's no SDC support in this project - I'll need to investigate that
