### ISSUE TITLE
includes using alias from Vite config

### ISSUE THREAD

**Issue by dhmax88** [larowlan/vite-plugin-twig-drupal#20]
I'm trying to use includes with an alias from vite, i.e.

```	
resolve: {
	alias: {
		'@templates': resolve(__dirname, '/src/templates'),
	},
},
```

so I can then do:

`{% include '@templates/button/button' %}` within storybook files.

But the alias is not being picked up within Storybook. Does anyone have this working?

**Comment by larowlan** [comment]
These are called namespaces in twig, see the docs in the README - https://github.com/larowlan/vite-plugin-twig-drupal?tab=readme-ov-file#installation

**Comment by dhmax88** [comment]
Thanks for the speedy reply @larowlan 

When using namespaces I run into the same issue and get this error:

```
import '/var/www/html/src/templates/typography/@templates/button/button';
```

which would suggest the namespace isn't functioning as expected

**Comment by larowlan** [comment]
Can you share your config? Thanks

**Comment by dhmax88** [comment]
I realise the issue, and it's most likely due to my own ignorance!

```
twig({
	namespaces: {
		templates: join(__dirname, '/src/templates'),
	},
}), 
```

the above adds the '@' in the plugin, so this is then used as `@templates/` in the storybook files. I was setting the @ in the namespace itself.

**Comment by larowlan** [comment]
Sweet! If I can update the readme at all to make it clearer, please let me know 👍
