### ISSUE TITLE
Storybook decorators

### ISSUE THREAD

**Issue by hirnschmalz** [larowlan/vite-plugin-twig-drupal#21]
Is there a way to make use of [Storybooks decorators](https://storybook.js.org/docs/writing-stories/decorators) to wrap the component with some additional HTML code that should not be shown in the HTML view of Storybook?

**Comment by larowlan** [comment]
I don't see why not? Have you tried it and it didn't work? If so what errors did you get

**Comment by hirnschmalz** [comment]
Sorry, my fault - wrong code 🤦 

Just in case anybody else is struggling. Decorators work like this

```js
  decorators:[
    (Story) => `
      <div class="grid">
        ${Story()}
      </div>
    `,
  ],
```

**Comment by larowlan** [comment]
Nice! Thanks for replying 👍
