### ISSUE TITLE
Macros support?

### ISSUE THREAD

**Issue by IHIutch** [larowlan/vite-plugin-twig-drupal#5]
Does this plugin support Twig macros? I'm trying to use one in `pagination/templates/pagination-unbounded`, but I'm getting the following error

`An error occurred whilst rendering /project/home/ihiutch/workspace/stories/pagination/templates/pagination-unbounded.twig: TypeError: Cannot read properties of undefined (reading 'valueOf')`

[Codesandbox](https://codesandbox.io/p/sandbox/busy-mountain-xw2x2t?file=%2Fstories%2Fpagination%2Fpagination.stories.js)

**Also, excuse the other files, I found this plugin and am in the midst of migrating (If I can get macros to work!)

**Comment by IHIutch** [comment]
I tried playing around with some simpler implementations and noticed that it seemed to work intermittently. But the error that came up (in browser) was always the same `fs.statSync` one

**Comment by larowlan** [comment]
Can you give https://github.com/larowlan/vite-plugin-twig-drupal/pull/6 a try? Test in the PR seems to show it working, even with self references. Took me a while to get it going because I naffed up the macro syntax in the test twig files :upside_down_face:

**Comment by larowlan** [comment]
Happy to make a release with #6 if that's easier for testing, it doesn't make things any worse

**Comment by IHIutch** [comment]
Seems to be working, locally. Thank you!

**Comment by larowlan** [comment]
Cutting a new tag

**Comment by larowlan** [comment]
https://github.com/larowlan/vite-plugin-twig-drupal/releases/tag/v1.0.2 should be on npm

**Comment by IHIutch** [comment]
Tyvm, this plugin has made working with Twig and Storybook so easy!
